app:
  host: "0.0.0.0"
  port: 9010
  log_level: "debug"
  redis_password: test
  redis_addr: "localhost:6379"
  redis_queue_name: "screenshot_queue"
  headless_browser_url: "http://localhost:7317"

database:
  host: "localhost"
  port: 5432
  username: "root"
  password: "test"
  name: "test"
  max_idle_connections: 2
  max_active_connections: 10
  max_connection_lifetime: 2

blog_storage:
  base_url: "localhost:9000"
  key: "MINIO_ACCESS_KEY"
  secret: "MINIO_SECRET_KEY"
  bucket: "snapify"
  location: "us"
  signed_duration: 5  # Minute
  is_secure: false
