app:
  host: "0.0.0.0"
  port: 9010
  log_level: "debug"

database:
  host: "database"
  port: 5432
  username: "root"
  password: "test"
  name: "test"
  max_idle_connections: 2
  max_active_connections: 10
  max_connection_lifetime: 2

rabbitmq:
  broker: "amqp://test:test@rabbitmq:5672/"
  default_queue: "snapify_tasks"
  result_backend: "amqp://test:test@rabbitmq:5672/"
  amqp:
    exchange: "snapify_exchange"
    exchange_type: "direct"
    binding_key: "snapify_tasks"
    prefetch_count: 5
  worker:
    name: "worker-1"
    count: 5

minio:
  base_url: "minio:9000"
  key: "MINIO_ACCESS_KEY"
  secret: "MINIO_SECRET_KEY"
  bucket: "snapify"
  location: "us"
  sign_duration: 5  # Minute
