app:
  host: "0.0.0.0"
  port: 9010
  log_level: "debug"
  redis_password: test
  redis_addr: "redis:6379"
  redis_queue_name: "screenshot_queue"
  headless_browser_url: "http://browser:7317"
  auth_token: "v2?KDqbV7hhy64oJUPWB9HVxb2ZH35oAQhb!DqI=Eyhiw9DL!7Qvl6hzqJ76eGk2SgPjC/MS93=u8hyZMX?PAlhyKN0L52ln=LnFhm9Lu4HxQVg1hVDRJ=u8GToCZwex??oFdMeA?2FEB-maAUIsZ92JlrQOwQgAYqS3RnpxqJrs7lbUlaKZLxQPRV13i/ZYrDyza!d!PwUMb4UK2a8oiTwqrd8Z/1jEVL?S2?YOr!DReaDMv/KgVWq6kJJ1DC3Y"

database:
  host: "database"
  port: 5432
  username: "root"
  password: "test"
  name: "test"
  max_idle_connections: 2
  max_active_connections: 10
  max_connection_lifetime: 2

blog_storage:
  base_url: "minio:9000"
  key: "MINIO_ACCESS_KEY"
  secret: "MINIO_SECRET_KEY"
  bucket: "snapify"
  location: "us"
  signed_duration: 5  # Minute
  is_secure: false
