version: '3.1'

services:
  snapify:
    image: s4kibs4mi/snapify:0.0.2
    command: ["serve", "--config_path", "/root/"]
    restart: on-failure
    ports:
      - 9010:9010
    volumes:
      - "./config.yml:/root/config.yml"
    depends_on:
      - database
      - rabbitmq
      - minio

  database:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: root
    volumes:
      - "./storage/pg/:/var/lib/postgresql/data/"

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
      MINIO_SECRET_KEY: "MINIO_SECRET_KEY"
    command: ["server", "/data"]
    volumes:
      - "./storage/minio/:/data/"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
    ports:
      - 5672:5672
      - 15672:15672
