version: '3.1'

services:
  snapify:
    image: s4kibs4mi/snapify:1.0.4
    command: ["serve", "--config_path", "/root/", "--config_name", "config"]
    restart: on-failure
    ports:
      - 9010:9010
    volumes:
      - "./config.yml:/root/config.yml"
    depends_on:
      - database
      - rabbitmq
      - minio
      - chrome-headless
    links:
      - chrome-headless
    networks:
      snapify_net:
        ipv4_address: 172.28.1.1

  chrome-headless:
    image: chromedp/headless-shell:latest
    ports:
      - 9223:9222
    networks:
      snapify_net:
        ipv4_address: 172.28.1.2

  database:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: root
    volumes:
      - "./storage/pg/:/var/lib/postgresql/data/"
    networks:
      snapify_net:
        ipv4_address: 172.28.1.3

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
      MINIO_SECRET_KEY: "MINIO_SECRET_KEY"
    command: ["server", "/data"]
    volumes:
      - "./storage/minio/:/data/"
    networks:
      snapify_net:
        ipv4_address: 172.28.1.4

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      snapify_net:
        ipv4_address: 172.28.1.5

networks:
  snapify_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
