// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/s4kibs4mi/snapify/ent/runtime.go

const (
	Version = "v0.11.8"                                         // Version of ent codegen.
	Sum     = "h1:M/M0QL1CYCUSdqGRXUrXhFYSDRJPsOOrr+RLEej/gyQ=" // Sum of ent codegen.
)
