// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/s4kibs4mi/snapify/ent/predicate"
	"github.com/s4kibs4mi/snapify/ent/screenshot"
	"github.com/s4kibs4mi/snapify/models"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeScreenshot = "Screenshot"
)

// ScreenshotMutation represents an operation that mutates the Screenshot nodes in the graph.
type ScreenshotMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	status        *models.Status
	url           *string
	stored_path   *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Screenshot, error)
	predicates    []predicate.Screenshot
}

var _ ent.Mutation = (*ScreenshotMutation)(nil)

// screenshotOption allows management of the mutation configuration using functional options.
type screenshotOption func(*ScreenshotMutation)

// newScreenshotMutation creates new mutation for the Screenshot entity.
func newScreenshotMutation(c config, op Op, opts ...screenshotOption) *ScreenshotMutation {
	m := &ScreenshotMutation{
		config:        c,
		op:            op,
		typ:           TypeScreenshot,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withScreenshotID sets the ID field of the mutation.
func withScreenshotID(id uuid.UUID) screenshotOption {
	return func(m *ScreenshotMutation) {
		var (
			err   error
			once  sync.Once
			value *Screenshot
		)
		m.oldValue = func(ctx context.Context) (*Screenshot, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Screenshot.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withScreenshot sets the old Screenshot of the mutation.
func withScreenshot(node *Screenshot) screenshotOption {
	return func(m *ScreenshotMutation) {
		m.oldValue = func(context.Context) (*Screenshot, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ScreenshotMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ScreenshotMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Screenshot entities.
func (m *ScreenshotMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ScreenshotMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ScreenshotMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Screenshot.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetStatus sets the "status" field.
func (m *ScreenshotMutation) SetStatus(value models.Status) {
	m.status = &value
}

// Status returns the value of the "status" field in the mutation.
func (m *ScreenshotMutation) Status() (r models.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Screenshot entity.
// If the Screenshot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreenshotMutation) OldStatus(ctx context.Context) (v models.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ScreenshotMutation) ResetStatus() {
	m.status = nil
}

// SetURL sets the "url" field.
func (m *ScreenshotMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *ScreenshotMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Screenshot entity.
// If the Screenshot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreenshotMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *ScreenshotMutation) ResetURL() {
	m.url = nil
}

// SetStoredPath sets the "stored_path" field.
func (m *ScreenshotMutation) SetStoredPath(s string) {
	m.stored_path = &s
}

// StoredPath returns the value of the "stored_path" field in the mutation.
func (m *ScreenshotMutation) StoredPath() (r string, exists bool) {
	v := m.stored_path
	if v == nil {
		return
	}
	return *v, true
}

// OldStoredPath returns the old "stored_path" field's value of the Screenshot entity.
// If the Screenshot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreenshotMutation) OldStoredPath(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStoredPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStoredPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStoredPath: %w", err)
	}
	return oldValue.StoredPath, nil
}

// ClearStoredPath clears the value of the "stored_path" field.
func (m *ScreenshotMutation) ClearStoredPath() {
	m.stored_path = nil
	m.clearedFields[screenshot.FieldStoredPath] = struct{}{}
}

// StoredPathCleared returns if the "stored_path" field was cleared in this mutation.
func (m *ScreenshotMutation) StoredPathCleared() bool {
	_, ok := m.clearedFields[screenshot.FieldStoredPath]
	return ok
}

// ResetStoredPath resets all changes to the "stored_path" field.
func (m *ScreenshotMutation) ResetStoredPath() {
	m.stored_path = nil
	delete(m.clearedFields, screenshot.FieldStoredPath)
}

// SetCreatedAt sets the "created_at" field.
func (m *ScreenshotMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ScreenshotMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Screenshot entity.
// If the Screenshot object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreenshotMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ScreenshotMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the ScreenshotMutation builder.
func (m *ScreenshotMutation) Where(ps ...predicate.Screenshot) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ScreenshotMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ScreenshotMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Screenshot, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ScreenshotMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ScreenshotMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Screenshot).
func (m *ScreenshotMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ScreenshotMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.status != nil {
		fields = append(fields, screenshot.FieldStatus)
	}
	if m.url != nil {
		fields = append(fields, screenshot.FieldURL)
	}
	if m.stored_path != nil {
		fields = append(fields, screenshot.FieldStoredPath)
	}
	if m.created_at != nil {
		fields = append(fields, screenshot.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ScreenshotMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case screenshot.FieldStatus:
		return m.Status()
	case screenshot.FieldURL:
		return m.URL()
	case screenshot.FieldStoredPath:
		return m.StoredPath()
	case screenshot.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ScreenshotMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case screenshot.FieldStatus:
		return m.OldStatus(ctx)
	case screenshot.FieldURL:
		return m.OldURL(ctx)
	case screenshot.FieldStoredPath:
		return m.OldStoredPath(ctx)
	case screenshot.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Screenshot field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScreenshotMutation) SetField(name string, value ent.Value) error {
	switch name {
	case screenshot.FieldStatus:
		v, ok := value.(models.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case screenshot.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case screenshot.FieldStoredPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStoredPath(v)
		return nil
	case screenshot.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Screenshot field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ScreenshotMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ScreenshotMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScreenshotMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Screenshot numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ScreenshotMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(screenshot.FieldStoredPath) {
		fields = append(fields, screenshot.FieldStoredPath)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ScreenshotMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ScreenshotMutation) ClearField(name string) error {
	switch name {
	case screenshot.FieldStoredPath:
		m.ClearStoredPath()
		return nil
	}
	return fmt.Errorf("unknown Screenshot nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ScreenshotMutation) ResetField(name string) error {
	switch name {
	case screenshot.FieldStatus:
		m.ResetStatus()
		return nil
	case screenshot.FieldURL:
		m.ResetURL()
		return nil
	case screenshot.FieldStoredPath:
		m.ResetStoredPath()
		return nil
	case screenshot.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Screenshot field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ScreenshotMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ScreenshotMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ScreenshotMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ScreenshotMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ScreenshotMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ScreenshotMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ScreenshotMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Screenshot unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ScreenshotMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Screenshot edge %s", name)
}
