// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Md Samiul Alim Sakib",
            "email": "s4kibs4mi@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/s4kibs4mi/snapify/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/screenshots": {
            "get": {
                "description": "Retrieve screenshots",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screenshots"
                ],
                "summary": "Retrieve screenshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Number of items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page index",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apimodels.RespScreenshotList"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/apimodels.RespScreenshotData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Queues a task to take screenshot of given URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screenshots"
                ],
                "summary": "Queues a task to take screenshot of given URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create screenshot payload",
                        "name": "\"\"",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apimodels.ReqScreenshotCreate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apimodels.RespScreenshot"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apimodels.RespScreenshotData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/screenshots/{screenshot_id}": {
            "get": {
                "description": "Retrieve screenshot info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "screenshots"
                ],
                "summary": "Retrieve screenshot info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apimodels.RespScreenshot"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apimodels.RespScreenshotData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apimodels.ReqScreenshotCreate": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "apimodels.RespScreenshot": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/apimodels.RespScreenshotData"
                }
            }
        },
        "apimodels.RespScreenshotData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "screenshot_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "apimodels.RespScreenshotList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apimodels.RespScreenshotData"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:9010",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Snapify",
	Description:      "A RESTful API service to take screenshot of any webpage.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
