// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Screenshot is the predicate function for screenshot builders.
type Screenshot func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)
